name: RunePvP
version: 1.1.0
main: aliuly\runepvp\Main
api: 1.10.0
load: POSTWORLD
# You have to have at least one of these...
softdepend: [SignShop,PocketMoney,MassiveEconomy,EconomyAPI]

description: A funny PvP manager plugin inspired by RuinPvP
author: aliuly

commands:
    runepvp:
        description: Show your RunePvP stats
        usage: "/runepvp"
        aliases: [rp]
        permission: runepvp.cmd

permissions:
    runepvp.cmd:
        default: true
        description: "Give players access to RunePvP command"
    runepvp.cmd.stats:
        default: true
        description: "Access to stats command"
    runepvp.cmd.stats.other:
        default: op
        description: "View other's stats"
    runepvp.cmd.top:
        default: true
        description: "View top players"
    runepvp.signs.place:
        default: op
        description: "Allow users to place RunePvP signs"
    runepvp.signs.place.stats:
        default: op
        description: "Allow users to place RunePvP signs for Stats"
    runepvp.signs.place.rankings:
        default: op
        description: "Allow users to place RunePvP signs for Rankings"
    runepvp.signs.place.onlineranks:
        default: op
        description: "Allow users to place RunePvP signs for Online ranks"
    runepvp.signs.place.shop:
        default: op
        description: "Allow users to place RunePvP signs for shops"
    runepvp.signs.place.casino:
        default: op
        description: "Allow users to place RunePvP signs for Casinos"
    runepvp.signs.use:
        default: op
        description: "Allow users to use RunePvP signs"
    runepvp.signs.use.stats:
        default: op
        description: "Allow users to use specific RunePvP signs"
    runepvp.signs.use.rankings:
        default: op
        description: "Allow users to use specific RunePvP signs"
    runepvp.signs.use.onlineranks:
        default: op
        description: "Allow users to use specific RunePvP signs"
    runepvp.signs.use.shop:
        default: op
        description: "Allow users to use specific RunePvP signs"
    runepvp.signs.use.casino:
        default: op
        description: "Allow users to use specific RunePvP signs"
